export const THEME = {
  SCREEN_GRADIENT: { START: "#1253AA", END: "#05243E" },
  WHITE_TEXT_COLOR: "#FFFFFF",
  DOT_UNACTIVE_COLOR: "#FFFFFF",
  DOT_ACTIVE_COLOR: "#1253AA",
  WHITE_COLOR: "#FFFFFF",
  BUTTON_COLOR: "#0EA5E9",
  SIGN_UP_IN_COLOR: "#63D9F3",
};
