export const THEME = {
  SCREEN_GRADIENT: { START: "#1253AA", END: "#05243E" },
  WHITE_TEXT_COLOR: "#FFFFFF",
  DOT_UNACTIVE_COLOR: "#FFFFFF",
  DOT_ACTIVE_COLOR: "#1253AA",
  WHITE_COLOR: "#FFFFFF",
};
